### ISSUE TITLE
hourly_weekcast Extractor not working as expected

### ISSUE THREAD

**Issue by DragonflyNet67** [T-Santos/WunderWeather#2]
Hi first of all thanky you very much for this great Wrapper. I found a problem with the hourly_weekcast Extractor. It does not return the exptected results as the WU-API hourly10day, where data for every single hour within 10 days is returned.

**Comment by T-Santos** [comment]
Hey! Glad you found it useful, sorry about the bug. I've updated the code, mind giving it another shot and confirming the fix? Thanks!

**Comment by DragonflyNet67** [comment]
Hey, thank you very much. I am amazed and impressed how fast you fixed this. I just tested it and it works like a charm. Thanks.

**Comment by DragonflyNet67** [comment]
Hey, thank you very much. 

I am really amazed and impressed how fast you fixed this. 

I just tested it and it works like a charm. 

 

I am currently programming a Python-QT based Weather program which sould look somehow like the Android App from Wunderground.

My private Weatherstation reports the Weatherdata to Wunderground every 5 Minutes. 

 

Thanks a lot. Your Wunderground Wrapper is absolutely great.

 

Nelson

**Comment by T-Santos** [comment]
Sounds like you have a cool project of your own going on, glad I could help. Happy coding!
