### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by kqi914** [T-Santos/WunderWeather#4]
-------------------------------------------
Python version: 3.7.0
WunderWeather version: 1.1.0
-------------------------------------------
Hello,

I am trying to create a python script to gather historical weather data from a certain location. First I wanted to do some basic forecasting scripts to get my feet wet but I have been having trouble getting those to work. 

For example when running:
```
from WunderWeather import weather
extractor = weather.Extract('apikey')
[location,current] = extractor.features("MA/Boston",(('geolookup',''),('now','')))
print("Current Temperature in %s is: %s" %(location.data.city,current.temp_f))
```
I get the error:

```
Traceback (most recent call last):
  File "/Users/user1/Desktop/WW.py", line 20, in <module>
    print("Current Temperature in %s is: %s" %(location.data.city,current.temp_f))
AttributeError: 'NoneType' object has no attribute 'data'
```

I am not sure if the key I am using is working as doing a simple URL request yields:
```
{
  "response": {
  "version":"0.1",
  "termsofService":"http://www.wunderground.com/weather/api/d/terms.html",
  "features": {
  }
		,
	"error": {
		"type": "keynotfound"
		,"description": "this key does not exist"
	}
	}
}
```

But the professor I am working with says it works as he is able to run a program using R using the same API key.

**Comment by T-Santos** [comment]
Hi, 

Thanks for showing interest in this package. 
Last I knew, the free API that backs this python wrapper has been decommissioned.

If you're doing a request and getting that response back "key doesn't exist" it sounds like either A) you're providing the key incorrectly or B) the Weather Underground API no longer exists and as a result this python wrapper will not work.

**Comment by T-Santos** [comment]
It looks like they've rebuilt the API quite a bit now that I look closer at it. The below should work but this package needs to be updated to handle the new url formats and responses. 

`import requests # learn more: https://python.org/pypi/requests
from pprint import pprint as pp
response = requests.get('https://api.weather.com/v2/pws/observations/current?stationId=KMAHANOV10&format=json&units=e&apiKey={}'.format(api_key))
pp(response.json())`

`{'observations': [{'country': 'US',
                   'epoch': 1556241966,
                   'humidity': 78,
                   'imperial': {'dewpt': 41,
                                'elev': 104,
                                'heatIndex': 48,
                                'precipRate': 0.0,
                                'precipTotal': 0.0,
                                'pressure': 29.97,
                                'temp': 48,
                                'windChill': 48,
                                'windGust': 3,
                                'windSpeed': 0},
                   'lat': 42.09263229,
                   'lon': -70.86485291,
                   'neighborhood': '1505Broadway',
                   'obsTimeLocal': '2019-04-25 21:26:06',
                   'obsTimeUtc': '2019-04-26T01:26:06Z',
                   'qcStatus': 1,
                   'realtimeFrequency': None,
                   'softwareType': 'Rainwise IP-100',
                   'solarRadiation': None,
                   'stationID': 'KMAHANOV10',
                   'uv': None,
                   'winddir': 180}]}`

**Comment by kqi914** [comment]
Sorry for the late reply. The api key given to me does work and after reading some [documentation](https://docs.google.com/document/d/15Ru_3wdMgpbM4aOCm-4qNAnRfjx2w-Ruw3lnr8Hnodk/edit) I managed to find the correct request formats.

Thanks!
